### ISSUE TITLE
Save all variables not straight forward

### ISSUE THREAD

**Issue by AnHeuermann** [ThummeTo/FMI.jl#68]
## Description
I want to simulate a FMU and save all varaibles in the results. For me this would be the default way to simulate a given FMU.

I have two problems:

a) I have to provide all variable names.
b) The data type returned by `fmiSimulate` can't be used to create a `DataFrame`, so I need to do it manually.

So my request would be to get a simple method to save all variables and to return a format that can be directly used by DataFrames.

```julia
fmu = fmiLoad("Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum")
allVariables = [fmu.modelDescription.modelVariables[i].name for i in 1:length(fmu.modelDescription.modelVariables)]
fmiInstantiate!(fmu)
success, simData = fmiSimulateME(fmu; recordValues=allVariables)
```

I would preferer to just use `success, simData = fmiSimulateME(fmu)` or `success, simData = fmiSimulateME(fmu; recordValues=true)`.
Collecting all variable names can be done internally as well.

```julia
julia> typeof(simData)
SavedValues{Float64, NTuple{1094, Float64}}

julia> DataFrame(simData)
ERROR: ArgumentError: no default `Tables.columns` implementation for type: SavedValues{Float64, NTuple{1094, Float64}}
```

I can convert it myself, but the object returned by the ODE solver was of type `SciMLBase.ODESolution` and can be used just fine in a data frame. I guess the callbacks used to filter the results is a problem. Not sure what is faster, adding `SavedValues` to Tables.column or just use the `ODESolution`.

**Comment by ThummeTo** [comment]
(a) The wish of recording all values of a FMU is (from my view) not the default case. We often work with FMUs with 10 000 and even more variables and this would be a significant slow down to record all of these by default. I think the default use-case would be more like recording all the system **states**. The problem is, that CS-FMUs can hide theire state value references, so basically we cannot access them in any case (we don't even know how much states there are in the FMU). So the fallback was to just record what is explicitely forced by the user.
Would it be an idea to provide an arguemnt `recordValues=:all` as shortcut to record everything?

(b) In the package DiffEqCallbacks.jl, the default return type for saving values during solving an ODE are `SavedValues`, so we basically take this as it is and return it to the user. I would not convert it in any case (because of performance, simulations with large output data will need long for conversion).
But I think we could provide a conversion command, that converts `SavedValues` to `DataFrame`, including some nice identifier names from the FMU's model description.

Please let me know what you thin about (a) and (b).
Thanks!

**Comment by AnHeuermann** [comment]
Both sound very good.

**Comment by ThummeTo** [comment]
This feature was added in 0.8.0, you can use the following symbols anywhere value references are needed:
- `:states` the model states 
- `:derivatives` the model state derivatives
- `:inputs` the model inputs
- `:outputs` the model outputs
- `:all` all variables
- `:none` no variables, same as `nothing`
